{"uid":"bb2e0b33520f0786","name":"test_add_product_to_cart","fullName":"tests.TestRemoveItem#test_add_product_to_cart","historyId":"393467ea44515a0a3bbcbff6ed3c633e","time":{"start":1728926914041,"stop":1728926914041,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562681faf02a <unknown>\n#1 0x562681c955e0 <unknown>\n#2 0x562681ccd921 <unknown>\n#3 0x562681cc92c5 <unknown>\n#4 0x562681d15df6 <unknown>\n#5 0x562681d15446 <unknown>\n#6 0x562681d098c3 <unknown>\n#7 0x562681cd76b3 <unknown>\n#8 0x562681cd868e <unknown>\n#9 0x562681f79a2b <unknown>\n#10 0x562681f7d9b1 <unknown>\n#11 0x562681f66225 <unknown>\n#12 0x562681f7e532 <unknown>\n#13 0x562681f4b38f <unknown>\n#14 0x562681f9df28 <unknown>\n#15 0x562681f9e0f3 <unknown>\n#16 0x562681fade7c <unknown>\n#17 0x7f1442e94ac3 <unknown>","statusTrace":"request = <SubRequest 'init_driver' for <Function test_add_product_to_cart>>\n\n    @pytest.fixture(scope=\"class\")\n    def init_driver(request):\n        # Инициализация драйвера\n>       driver = webdriver.Chrome()\n\nconftest.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:212: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:299: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f744e86a1d0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...\\\\n#15 0x562681f9e0f3 \\\\u003Cunknown>\\\\n#16 0x562681fade7c \\\\u003Cunknown>\\\\n#17 0x7f1442e94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x562681faf02a <unknown>\nE       #1 0x562681c955e0 <unknown>\nE       #2 0x562681ccd921 <unknown>\nE       #3 0x562681cc92c5 <unknown>\nE       #4 0x562681d15df6 <unknown>\nE       #5 0x562681d15446 <unknown>\nE       #6 0x562681d098c3 <unknown>\nE       #7 0x562681cd76b3 <unknown>\nE       #8 0x562681cd868e <unknown>\nE       #9 0x562681f79a2b <unknown>\nE       #10 0x562681f7d9b1 <unknown>\nE       #11 0x562681f66225 <unknown>\nE       #12 0x562681f7e532 <unknown>\nE       #13 0x562681f4b38f <unknown>\nE       #14 0x562681f9df28 <unknown>\nE       #15 0x562681f9e0f3 <unknown>\nE       #16 0x562681fade7c <unknown>\nE       #17 0x7f1442e94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"init_driver","time":{"start":1728926914041,"stop":1728926914228,"duration":187},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562681faf02a <unknown>\n#1 0x562681c955e0 <unknown>\n#2 0x562681ccd921 <unknown>\n#3 0x562681cc92c5 <unknown>\n#4 0x562681d15df6 <unknown>\n#5 0x562681d15446 <unknown>\n#6 0x562681d098c3 <unknown>\n#7 0x562681cd76b3 <unknown>\n#8 0x562681cd868e <unknown>\n#9 0x562681f79a2b <unknown>\n#10 0x562681f7d9b1 <unknown>\n#11 0x562681f66225 <unknown>\n#12 0x562681f7e532 <unknown>\n#13 0x562681f4b38f <unknown>\n#14 0x562681f9df28 <unknown>\n#15 0x562681f9e0f3 <unknown>\n#16 0x562681fade7c <unknown>\n#17 0x7f1442e94ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/Kassa/Kassa/conftest.py\", line 8, in init_driver\n    driver = webdriver.Chrome()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('init_driver', 'base_url')"},{"name":"suite","value":"tests"},{"name":"subSuite","value":"TestRemoveItem"},{"name":"host","value":"fv-az1393-657"},{"name":"thread","value":"2145-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"44b71dce6f6dd89f","reportUrl":"https://Neonila96.github.io/Kassa/5//#testresult/44b71dce6f6dd89f","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x558f7c7c702a <unknown>\n#1 0x558f7c4ad5e0 <unknown>\n#2 0x558f7c4e5921 <unknown>\n#3 0x558f7c4e12c5 <unknown>\n#4 0x558f7c52ddf6 <unknown>\n#5 0x558f7c52d446 <unknown>\n#6 0x558f7c5218c3 <unknown>\n#7 0x558f7c4ef6b3 <unknown>\n#8 0x558f7c4f068e <unknown>\n#9 0x558f7c791a2b <unknown>\n#10 0x558f7c7959b1 <unknown>\n#11 0x558f7c77e225 <unknown>\n#12 0x558f7c796532 <unknown>\n#13 0x558f7c76338f <unknown>\n#14 0x558f7c7b5f28 <unknown>\n#15 0x558f7c7b60f3 <unknown>\n#16 0x558f7c7c5e7c <unknown>\n#17 0x7ffb8ec94ac3 <unknown>","time":{"start":1728925936782,"stop":1728925936782,"duration":0}},{"uid":"4ce43d9e489867dc","reportUrl":"https://Neonila96.github.io/Kassa/4//#testresult/4ce43d9e489867dc","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x556cc4c5102a <unknown>\n#1 0x556cc49375e0 <unknown>\n#2 0x556cc496f921 <unknown>\n#3 0x556cc496b2c5 <unknown>\n#4 0x556cc49b7df6 <unknown>\n#5 0x556cc49b7446 <unknown>\n#6 0x556cc49ab8c3 <unknown>\n#7 0x556cc49796b3 <unknown>\n#8 0x556cc497a68e <unknown>\n#9 0x556cc4c1ba2b <unknown>\n#10 0x556cc4c1f9b1 <unknown>\n#11 0x556cc4c08225 <unknown>\n#12 0x556cc4c20532 <unknown>\n#13 0x556cc4bed38f <unknown>\n#14 0x556cc4c3ff28 <unknown>\n#15 0x556cc4c400f3 <unknown>\n#16 0x556cc4c4fe7c <unknown>\n#17 0x7f44b5694ac3 <unknown>","time":{"start":1728925601612,"stop":1728925601612,"duration":0}}]},"tags":["@pytest.mark.usefixtures('init_driver', 'base_url')"]},"source":"bb2e0b33520f0786.json","parameterValues":[]}